version: '3.0'

services:
  grafana:
    container_name: 'ni-slnotebook-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.4.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/ni-slnotebook-datasource
      - ./provisioning:/etc/grafana/provisioning
